### ISSUE TITLE
Blender 3.1 error

### ISSUE THREAD

**Issue by jetdog8808** [Arminando/GameRig#16]
Tried GameRig in blender 3.1 and got this error.

<details>
<summary>Console Error</summary>
<br>
registering <class 'rigify.feature_sets.GameRig_0_0_3.gamerig_generate.GAMERIG_OT_generate'>
Rigify Error: Could not call function 'register' of feature set 'GameRig_0_0_3': exception occurred.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\rigify\feature_set_list.py", line 113, in call_function_safe
    return func(*args, **kwargs)
  File "C:\Users\Jet\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\rigify\GameRig_0_0_3\__init__.py", line 31, in register
    m.register()
  File "C:\Users\Jet\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\rigify\GameRig_0_0_3\ui.py", line 383, in register
    bpy.types.DATA_PT_rigify_buttons.prepend(draw_gamerig_rigify_button)
AttributeError: 'module' object has no attribute 'DATA_PT_rigify_buttons'

</details>

I'm still new to blender but took a shot at fixing it.

Looks rigify changed some class names. changed "DATA_PT_rigify_buttons" too "BONE_PT_rigify_buttons" for the lines below. And so far it seams to be working fine.

https://github.com/Arminando/GameRig/blob/bb9469e3a41e578974deaa5d58dc49e05efdba94/ui.py#L425
https://github.com/Arminando/GameRig/blob/bb9469e3a41e578974deaa5d58dc49e05efdba94/ui.py#L436

**Comment by jetdog8808** [comment]
looks like there is a lot more that would have to be fixed.
