### ISSUE TITLE
Look at controller not working on generated face.skin_eye rig

### ISSUE THREAD

**Issue by nlerin** [Arminando/GameRig#17]
The generated eye rig does not follow the lookat controller when moved around.

Looks like the DEF-eye joints are missing copy location and rotation constraints to the MCH-eye joints

Test with latest release https://github.com/Arminando/GameRig/releases/tag/v0.3.3.1
Blender 3.3.1 and rigify 0.6.6

**Comment by nlerin** [comment]
Thanks for the quick fix.

It works when "Eyeball and Iris deforms" is enabled, if it's disabled I get the following error

```
Rigify: failed to generate rig.
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\rigify\ui.py", line 798, in execute
    generate.generate_rig(context, metarig)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\rigify\generate.py", line 617, in generate_rig
    raise e
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\rigify\generate.py", line 605, in generate_rig
    generator.generate()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\rigify\generate.py", line 520, in generate
    self.invoke_rig_bones()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\rigify\base_generate.py", line 384, in invoke_rig_bones
    self.__run_object_stage('rig_bones')
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\rigify\base_generate.py", line 273, in __run_object_stage
    rig.rigify_invoke_stage(method_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\rigify\utils\metaclass.py", line 135, in rigify_invoke_stage
    getattr(self, method_name)()
  File "C:\Users\nilsl\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\rigify\GameRig_0_3_3_2\rigs\game\face\skin_eye.py", line 28, in rig_deform_chain
    self.make_constraint(self.bones.deform.eye, 'COPY_LOCATION', self.bones.mch.master)
AttributeError: 'BoneDict' object has no attribute 'eye'
Error: Generation has thrown an exception: 'BoneDict' object has no attribute 'eye'
```

I'm not sure what that setting is supposed to do exactly but it would be nice to have the option to not generate the iris and master deformation bones and just have one deform joint per eye (DEF-eye.L/R)

**Comment by Arminando** [comment]
Thanks for reporting the errors.
I can't seem to reproduce it. Do you mind sending me the file with the metarig so I can debug using it?

**Comment by Arminando** [comment]
I also like the idea of having only one bone per eye. Will think about how I can get that option in

**Comment by nlerin** [comment]
For sure, attaching it here saved right before running generate rig.
[face_skineye_error.zip](https://github.com/Arminando/GameRig/files/9922645/face_skineye_error.zip)

**Comment by Arminando** [comment]
Thanks for the file. It should work fine now
